server:
  port: 9091
  shutdown: graceful

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  application:
    name: websocket

  profiles:
    include:
      - persistence

logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.messaging: TRACE
    org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler: TRACE


