server:
  port: 9090

spring:
  application:
    name: api

  profiles:
    include:
      - persistence

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 26379
      ttl: 300
