spring:

  application:
    name: persistence

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    hikari:
      max-lifetime: 250000 #250 sec
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/near_connect?autoReconnect=true
    username: near_connect_user
    password: near_connect_user

  flyway:
    enabled: true
    out-of-order: true
    baseline-on-migrate: true
    locations:
      - "classpath:db/migration/near_connect"

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 26379
      ttl: 300
